<%@ Page Language="C#" MasterPageFile="~/admin/admin.master" AutoEventWireup="true" CodeFile="videosList.aspx.cs" Inherits="admin_videosList" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="bodyClass" Runat="Server">
<body id="admin">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<asp:ScriptManager ID="videoListScriptManager" runat="server" />
<!-- Page Wrapper -->
<div id="pageWrapper">
    <!-- Page -->
    <div id="page">
    <div style="float: left;"><asp:ImageButton id="backToMainIB" runat="server" ImageUrl="../Images/miniRibbon/back_32.png" onClick="backToMain" ToolTip="Back To Videos Main" /></div>
    <div style="float: left; margin: 9px 0px 21px 6px;"><asp:LinkButton id="backToMainLB" runat="server" Text="Back To Videos Home" onClick="backToMain" /> </div>
    <div style="float: left; margin-left: 21px;"><asp:ImageButton id="backToVidListIB" runat="server" ImageUrl="../Images/miniRibbon/back_32.png" onClick="backToVidList" ToolTip="Back To Videos Main" /></div>
    <div style="float: left; margin: 9px 0px 21px 6px;"><asp:LinkButton id="backToVidListLB" runat="server" Text="Back To List Home" onClick="backToVidList" /> </div>

    <div style="float: right;"><h3><asp:Label ID="h3Title" runat="server" /></h3></div>
<asp:Label id="debuging" runat="server" />
<asp:Label ID="newEdError" runat="server" style="display:none" />
<asp:Label ID="dbErrorMessage" runat="server" />
 <div id="deleteConfirmDiv" runat="server" style="display:none;"> <asp:Button ID="btnDeleteConfirm" runat="server" OnClick="deleteTrue" CssClass="formBtn" Text="Confirm Delete" /> <asp:Button ID="btnCancelDelete" runat="server" OnClick="cancelDelete" Text="Cancel" /><asp:Label ID="deleteConfirmation" runat="server" /></div>
<!-- Start Video Grid View -->
         <asp:GridView ID="videoInfoGrid" runat="server"
            AutoGenerateColumns="false" AllowSorting="True" AllowPaging="true" PageSize="10"
            AutoGenerateDeleteButton="true" 
            onPageIndexChanging = "videoInfoGrid_PageIndexChanging"
            onsorting="videoInfoGrid_Sorting"
            onSelectedIndexChanged = "videoInfoGrid_SelectedIndexChanged"
            OnRowDeleting="videoInfoGrid_RowDeleting">
            <Columns>
                <asp:BoundField DataField="videoInfoID" HeaderText="Video ID" HeaderStyle-HorizontalAlign="Left" SortExpression="videoInfoID" />
                <asp:BoundField DataField="videoName" HeaderText="Name" HeaderStyle-HorizontalAlign="Left" SortExpression="videoName" />
                <asp:BoundField DataField="description" HeaderText="Description" HeaderStyle-HorizontalAlign="Left" SortExpression="description" />
                <asp:BoundField DataField="categoryName" HeaderText="Category" HeaderStyle-HorizontalAlign="Left" SortExpression="categoryName" />
                <asp:BoundField DataField="authorName" HeaderText="Author" HeaderStyle-HorizontalAlign="Left" SortExpression="authorName" />
                <asp:ButtonField CommandName="Select" Text="Select" />
            </Columns>
       </asp:GridView> 
<!-- End Video Grid View -->
<!-- Start Video Detail View -->
       <asp:Label ID="videoDetailError" runat="server" />
       <asp:DetailsView ID="videoDetail" runat="server" AutoGenerateRows="False"
            onmodechanging="videoDetail_ModeChanging"
            onitemupdating="videoDetail_ItemUpdating">
             <FieldHeaderStyle Width="110px" HorizontalAlign="right" BackColor="#ededed" CssClass="headerPad" />
             <Fields>
                <asp:CommandField ShowEditButton="True" ValidationGroup="videoEdit" EditText="Edit Video Details" ButtonType="Button" ControlStyle-CssClass="formBtn" />
                    <asp:TemplateField HeaderText="Name">
                        <EditItemTemplate>
                            <asp:TextBox ID="videoNameEdit" runat="server" Text='<%# Bind("videoName") %>' />
                            <asp:RequiredFieldValidator ID="editVidNameReq" runat="server"
        	                         ControlToValidate="videoNameEdit"
        	                         ErrorMessage="Video name required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidNameReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidNameReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideoNameEdit" runat="server"
        	                        ControlToValidate="videoNameEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideoNameEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideoNameEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoNameDetail" runat="server" Text='<%# Bind("videoName") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Length">
                        <EditItemTemplate>
                            <asp:TextBox ID="videoLenghtEdit" runat="server" Text='<%# Bind("lenght") %>' />
                            <asp:RequiredFieldValidator ID="editVidLenghtReq" runat="server"
        	                         ControlToValidate="videoLenghtEdit"
        	                         ErrorMessage="Video Lenght required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidLenghtReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidLenghtReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideoLenghtEdit" runat="server"
        	                        ControlToValidate="videoLenghtEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideoLenghtEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideoLenghtEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoLenghtDetail" runat="server" Text='<%# Bind("lenght") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField HeaderText="Width">
                        <EditItemTemplate>
                            <asp:TextBox ID="videoWidthEdit" runat="server" Text='<%# Bind("width") %>' />
                            <asp:RequiredFieldValidator ID="editVidWidthReq" runat="server"
        	                         ControlToValidate="videoWidthEdit"
        	                         ErrorMessage="Video width required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidwidthReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidWidthReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideowidthEdit" runat="server"
        	                        ControlToValidate="videoWidthEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideowidthEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideowidthEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoWidthDetail" runat="server" Text='<%# Bind("width") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                      <asp:TemplateField HeaderText="Height">
                        <EditItemTemplate>
                            <asp:TextBox ID="videoHeightEdit" runat="server" Text='<%# Bind("height") %>' />
                            <asp:RequiredFieldValidator ID="editVidHeightReq" runat="server"
        	                         ControlToValidate="videoHeightEdit"
        	                         ErrorMessage="Video height required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidheightReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidHeightReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideoheightEdit" runat="server"
        	                        ControlToValidate="videoHeightEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideoheightEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideoheightEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoHeightDetail" runat="server" Text='<%# Bind("height") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField HeaderText="Author">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlVidAuthorEdit" runat="server" CssClass="dropdownmenu" />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoAuthorDetail" runat="server" Text='<%# Bind("authorName") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Edition">
                        <EditItemTemplate>
                            <asp:CheckBoxList ID="cbVidEdEdit" runat="server" RepeatDirection="Horizontal" />
                        </EditItemTemplate>
                        <ItemTemplate>
                        <asp:CheckBoxList ID="videoEdDetail" runat="server" RepeatDirection="Horizontal" Enabled="false" ></asp:CheckBoxList>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Category">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlVidCatEdit" runat="server" CssClass="dropdownmenu" />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoCatLbl" runat="server" Text='<%# Bind("categoryName") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="SC Video#">
                        <EditItemTemplate>
                            <asp:TextBox ID="videoSCVNEdit" runat="server" Text='<%# Bind("link") %>' />
                            <asp:RequiredFieldValidator ID="editVidSCVNReq" runat="server"
        	                         ControlToValidate="videoSCVNEdit"
        	                         ErrorMessage="Video link required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidSCVNReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidSCVNReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideoSCVNEdit" runat="server"
        	                        ControlToValidate="videoSCVNEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideoSCVNEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideoSCVNEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoSCVNLbl" runat="server" Text='<%# Bind("link") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="SC File Name">
                        <EditItemTemplate>
                            <asp:TextBox ID="videoSCFNEdit" runat="server" Text='<%# Bind("fileName") %>' />
                            <asp:RequiredFieldValidator ID="editVidSCFNReq" runat="server"
        	                         ControlToValidate="videoSCFNEdit"
        	                         ErrorMessage="Video file name required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidSCFNReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidSCFNReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideoSCFNEdit" runat="server"
        	                        ControlToValidate="videoSCFNEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideoSCFNEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideoSCFNEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoSCFNLbl" runat="server" Text='<%# Bind("fileName") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Key Words">
                        <EditItemTemplate>
                            <asp:TextBox ID="videokeyWrdsEdit" runat="server" Text='<%# Bind("keyWords") %>' />
                            <asp:RequiredFieldValidator ID="editVidkeyWrdsReq" runat="server"
        	                         ControlToValidate="videokeyWrdsEdit"
        	                         ErrorMessage="Video key words required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidkeyWrdsReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidkeyWrdsReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideokeyWrdsEdit" runat="server"
        	                        ControlToValidate="videokeyWrdsEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideokeyWrdsEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideokeyWrdsEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videokeyWrdsLbl" runat="server" Text='<%# Bind("keyWords") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Description">
                        <EditItemTemplate>
                            <asp:TextBox ID="videoDescEdit" runat="server" Text='<%# Bind("description") %>' Rows="7" TextMode="MultiLine" style="width: 300px;" />
                            <asp:RequiredFieldValidator ID="editVidDescReq" runat="server"
        	                         ControlToValidate="videoDescEdit"
        	                         ErrorMessage="Video Desc required to update."
        	                         SetFocusOnError="true" Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="editVidDescReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editVidDescReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpVideoDescEdit" runat="server"
        	                        ControlToValidate="videoDescEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),_,!,@,.,#,\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" ValidationGroup="videoEdit" />
        	                      <cc1:ValidatorCalloutExtender ID="regExpVideoDescEdit_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpVideoDescEdit"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="videoDescDetail" runat="server" Text='<%# Bind("description") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Assoc. Imp. Steps">
                        <EditItemTemplate>
                            <asp:CheckBoxList ID="videoImpStepsCBEdit" runat="server" RepeatDirection="Horizontal" RepeatColumns="2"></asp:CheckBoxList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:ListBox ID="videoImpStepsDetail" runat="server" Enabled="false" ></asp:ListBox>
                        </ItemTemplate>
                    </asp:TemplateField>
            </Fields>
            <HeaderTemplate>
                    Video Name: <%#Eval("videoName") %>
                </HeaderTemplate>
                <AlternatingRowStyle cssClass="alternateRow" />
        </asp:DetailsView>
    <!-- /Page -->
    </div>
<!--/Page Wrapper -->
</div>
</asp:Content>

