<%@ Page Language="C#" MasterPageFile="~/admin/admin.master" AutoEventWireup="true" CodeFile="videosAuth.aspx.cs" Inherits="admin_videosAuth" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="bodyClass" Runat="Server">
<body id="admin">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<asp:ScriptManager ID="videoEdListScriptManager" runat="server" />
<!-- Page Wrapper -->
<div id="pageWrapper">
    <!-- Page -->
    <div id="page">
     <div style="float: left;"><asp:ImageButton id="backToMainIB" runat="server" ImageUrl="../Images/miniRibbon/back_32.png" onClick="backToMain" ToolTip="Back To Videos Main" /></div>
    <div style="float: left; margin: 9px 0px 21px 6px;"><asp:LinkButton id="backToMainLB" runat="server" Text="Back To Videos Home" onClick="backToMain" /> </div>
    <div style="float: right;"><h3><asp:Label ID="h3Title" runat="server" /></h3></div>
<asp:Label id="debuging" runat="server" />
<asp:Label ID="newEdError" runat="server" style="display:none" />
<asp:Label ID="dbErrorMessage" runat="server" />
 <div id="deleteConfirmDiv" runat="server" style="display:none;"> <asp:Button ID="btnDeleteConfirm" runat="server" OnClick="deleteTrue" CssClass="formBtn" Text="Confirm Delete" /> <asp:Button ID="btnCancelDelete" runat="server" OnClick="cancelDelete" Text="Cancel" /><asp:Label ID="deleteConfirmation" runat="server" /></div>
    <!-- Start Video Author Grid View -->
        <asp:GridView ID="authorGrid" runat="server"
             AutoGenerateDeleteButton="true"
             AutoGenerateEditButton="true"
             AutoGenerateColumns="false"
             onRowEditing="authorGrid_RowEditing"
             onRowCancelingEdit="authorGrid_RowCancelingEdit"
             onRowUpdating="authorGrid_RowUpdating"
             OnRowDeleting="author_RowDeleting"
             datakeynames="videoAuthID">
                <Columns>
                    <asp:TemplateField HeaderText="Video Author" HeaderStyle-HorizontalAlign="Left">
                        <EditItemTemplate>
                            <asp:TextBox ID="authorNameEdit" Text='<%# Bind("authorName")%>' runat="server"></asp:TextBox>
                                  <asp:RequiredFieldValidator ID="editauthorNameReq" runat="server"
        	                         ControlToValidate="authorNameEdit"
        	                         ErrorMessage="Video author name required to update."
        	                         SetFocusOnError="true" Display="None" />
        	                      <cc1:ValidatorCalloutExtender ID="editauthorNameReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editauthorNameReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpressioneditAuthorName" runat="server"
        	                        ControlToValidate="authorNameEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,!,@,.,#'\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" />
        	                      <cc1:ValidatorCalloutExtender ID="editAuthorName_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpressioneditAuthorName"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <InsertItemTemplate>
                            <asp:TextBox ID="authorNameInsert" runat="server" Text='<%# Bind("authorName") %>'></asp:TextBox>
                        </InsertItemTemplate>
                        <ItemTemplate>
                           <asp:Label ID="authorNameLabel" runat="server" Text='<%# Bind("authorName") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Author Image" HeaderStyle-HorizontalAlign="Left"> 
                        <EditItemTemplate>
                            <div id="divShowUpAuth" runat="server" style="display:none;">
                            <asp:FileUpload ID="fileUploadAuthorEdit" runat="server" />
                            </div>
                            <div id="divShowStaticAuth" runat="server">
                                <asp:Image ID="authImageEdit" runat="server" ImageUrl='<%# "~/Images/uploads/" + Eval("authImage") %>' /><br />
                                <asp:Label ID="authorImageSession" runat="server" Text='<%# Bind("authImage") %>' /><br />
                                <asp:Button ID="btnShowUpAuthEdit" runat="server" Text="Change" OnClick="changeAuthEidtImage" CssClass="formBtn" />
                            </div>
                            <asp:Label ID="editUploadError" runat="server" />
                        </EditItemTemplate>
                        <InsertItemTemplate>
                            <asp:TextBox ID="authorImageInsert" runat="server" Text='<%# Bind("authImage") %>'></asp:TextBox>
                        </InsertItemTemplate>
                        <ItemTemplate>
                           <asp:Image ID="authorImage" runat="server" ImageUrl='<%# "~/Images/uploads/" + Eval("authImage")%>' />
                        </ItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField HeaderText="Author Title" HeaderStyle-HorizontalAlign="Left">
                        <EditItemTemplate>
                            <asp:TextBox ID="authorTitleEdit" Text='<%# Bind("authTitle")%>' runat="server" MaxLength="100"></asp:TextBox>
        	                      <asp:RegularExpressionValidator ID="regExpressioneditAuthorTitle" runat="server"
        	                        ControlToValidate="authorTitleEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,(,),!,@,.,#'\-,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" />
        	                      <cc1:ValidatorCalloutExtender ID="editAuthorTitle_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpressioneditAuthorTitle"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <InsertItemTemplate>
                            <asp:TextBox ID="authorTitleInsert" runat="server" Text='<%# Bind("authTitle") %>'></asp:TextBox>
                        </InsertItemTemplate>
                        <ItemTemplate>
                           <asp:Label ID="authorTitleLabel" runat="server" Text='<%# Bind("authTitle") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                 <AlternatingRowStyle cssClass="alternateRow" />
             </asp:GridView>
    <!-- / Page -->
    </div>
<!-- / Page Wrapper -->
</div>
</asp:Content>

