<%@ Page Language="C#" MasterPageFile="~/admin/admin.master" AutoEventWireup="true" CodeFile="videosEd.aspx.cs" Inherits="admin_videosEd" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="bodyClass" Runat="Server">
<body id="admin">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<asp:ScriptManager ID="videoEdListScriptManager" runat="server" />
<!-- Page Wrapper -->
<div id="pageWrapper">
    <!-- Page -->
    <div id="page">
<div style="float: left;"><asp:ImageButton id="backToMainIB" runat="server" ImageUrl="../Images/miniRibbon/back_32.png" onClick="backToMain" ToolTip="Back To Videos Main" /></div>
    <div style="float: left; margin: 9px 0px 21px 6px;"><asp:LinkButton id="backToMainLB" runat="server" Text="Back To Videos Home" onClick="backToMain" /> </div>
    <div style="float: right;"><h3><asp:Label ID="h3Title" runat="server" /></h3></div>
<asp:Label id="debuging" runat="server" />
<asp:Label ID="newEdError" runat="server" style="display:none" />
<asp:Label ID="dbErrorMessage" runat="server" />
 <div id="deleteConfirmDiv" runat="server" style="display:none;"> <asp:Button ID="btnDeleteConfirm" runat="server" OnClick="deleteTrue" CssClass="formBtn" Text="Confirm Delete" /> <asp:Button ID="btnCancelDelete" runat="server" OnClick="cancelDelete" Text="Cancel" /><asp:Label ID="deleteConfirmation" runat="server" /></div>
<!-- Start Video Edition Grid View -->
         <asp:GridView ID="videoEdGrid" runat="server"
             AutoGenerateDeleteButton="true"
             AutoGenerateEditButton="true"
             AutoGenerateColumns="false"
             onRowEditing="editionGrid_RowEditing"
             onRowCancelingEdit="editionGrid_RowCancelingEdit"
             onRowUpdating="editionGrid_RowUpdating"
             OnRowDeleting="edition_RowDeleting"
             datakeynames="videoEdID">
                <Columns>
                    <asp:TemplateField HeaderText="Video Edition" HeaderStyle-HorizontalAlign="Left"> 
                        <EditItemTemplate>
                            <asp:TextBox ID="editionNameEdit" Text='<%# Bind("edition")%>' runat="server"></asp:TextBox>
                                  <asp:RequiredFieldValidator ID="editEdNameReq" runat="server"
        	                         ControlToValidate="editionNameEdit"
        	                         ErrorMessage="Video edition name required to update."
        	                         SetFocusOnError="true" Display="None" />
        	                      <cc1:ValidatorCalloutExtender ID="editEdNameReq_ValidatorCalloutExtender" 
                                     runat="server" Enabled="True" TargetControlID="editEdNameReq"
                                     HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
        	                      <asp:RegularExpressionValidator ID="regExpressioneditEdName" runat="server"
        	                        ControlToValidate="editionNameEdit"
        	                        ValidationExpression="^\s*[a-zA-Z0-9,\s,?,\,,',;,:,!,@,.,\-,#,&]+\s*$"
        	                        ErrorMessage="You have entered characters that are not allowed."
        	                        Display="None" />
        	                      <cc1:ValidatorCalloutExtender ID="editEdition_ValidatorCalloutExtender" 
                                    runat="server" Enabled="True" TargetControlID="regExpressioneditEdName"
                                    HighlightCssClass="fieldError">
                                  </cc1:ValidatorCalloutExtender>
                        </EditItemTemplate>
                        <InsertItemTemplate>
                            <asp:TextBox ID="editionNameInsert" runat="server" Text='<%# Bind("edition") %>'></asp:TextBox>
                        </InsertItemTemplate>
                        <ItemTemplate>
                           <asp:Label ID="editionNameLabel" runat="server" Text='<%# Bind("edition") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Video Logo Link" HeaderStyle-HorizontalAlign="Left"> 
                        <EditItemTemplate>
                             <div id="divShowUpEd" runat="server" style="display:none;">
                            <asp:FileUpload ID="fileUploadEdEdit" runat="server" />
                            </div>
                            <div id="divShowStaticEd" runat="server">
                                <asp:Image ID="edImageEdit" runat="server" ImageUrl='<%# "~/Images/uploads/" + Eval("editionLogo") %>' /><br />
                                <asp:Label ID="edImageSession" runat="server" Text='<%# Bind("editionLogo") %>' /><br />
                                <asp:Button ID="btnShowUpEdEdit" runat="server" Text="Change" OnClick="changeEdEidtImage" CssClass="formBtn" />
                            </div>
                            <asp:Label ID="editEdUploadError" runat="server" />
                        </EditItemTemplate>
                        <InsertItemTemplate>
                            <asp:TextBox ID="editionLogoInsert" runat="server" Text='<%# Bind("editionLogo") %>'></asp:TextBox>
                        </InsertItemTemplate>
                        <ItemTemplate>
                           <asp:Image ID="editionLogoImage" runat="server"  ImageUrl='<%# "~/Images/uploads/" + Eval("editionLogo") %>' AlternateText="LeonardoMD Edition Logo" />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                 <AlternatingRowStyle cssClass="alternateRow" />
             </asp:GridView>
    <!--/Page-->
    </div>
<!-- /Page Wrapper -->
</div>
</asp:Content>

